@ With the exception of Link standby, none of the below texts are used

gTest_MissedTurn::
    .string "错过回合$"

gText_LinkStandby4::
    .string "正在等待连接！$"

gText_WinnerIsPlayersMonCongrats::
    .string "冠军是{STR_VAR_1}的{STR_VAR_2}！\n恭喜！$"

gText_WinnerIsPlayersMon::
    .string "冠军是{STR_VAR_1}的{STR_VAR_2}！{0xFC 9}$"

gText_PrimaryJudgingNumX::
    .string "第1轮评审：No.{STR_VAR_1}{0xFC 9}$"

gText_SecondaryJudgingNumX::
    .string "第2轮评审：No.{STR_VAR_1}{0xFC 9}$"

gText_SetEventNumX::
    .string "自定赛：No.{STR_VAR_1}{0xFC 9}$"

gText_MoveUsedMostOften::
    .string "最常用的招式：\n{STR_VAR_1}{0xFC 9}$"

gText_MostImpressiveMon::
    .string "最出色的宝可梦：\n{STR_VAR_1}的{STR_VAR_2}{0xFC 9}$"

gText_SetEventNumX2::
    .string "自定赛：No.{STR_VAR_1}{0xFC 9}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
    .string "无法制作连接电视节目，\n因为训练家已断开连接。{0xFC 9}$"
