@ Contest move effect descriptions

gText_HighlyAppealingMove::
	.string "能够吸引人的表演。$"

gText_UserMoreEasilyStartled::
	.string "虽然能够演出很好的表演，\n"
	.string "但是之后会更容易受干扰。$"

gText_GreatAppealButNoMoreToEnd::
	.string "极具吸引力的表演，\n"
	.string "但是此后无法再进行表演。$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "即使重复演出也不会\n"
	.string "让评委感到无聊。$"

gText_AvoidStartledByOthersOnce::
	.string "即使被之后的宝可梦干扰\n"
	.string "也会挺住一次。$"

gText_AvoidStartledByOthers::
	.string "即使被之后的宝可梦干扰\n"
	.string "也会挺住。$"

gText_AvoidStartledByOthersLittle::
	.string "能够稍稍避免受到\n"
	.string "被其他宝可梦干扰。$"

gText_UserLessLikelyStartled::
	.string "在表演这个招式之后\n"
	.string "宝可梦会变得不易受干扰。$"

gText_SlightlyStartleFrontMon::
	.string "稍稍干扰在自己之前表演的\n"
	.string "宝可梦。$"

gText_SlightlyStartleAppealed::
	.string "稍稍干扰表演完成的\n"
	.string "所有宝可梦。$"

gText_StartleAppealedBeforeUser::
	.string "干扰在自己之前表演的\n"
	.string "宝可梦。$"

gText_StartleAllAppealed::
	.string "干扰表演完成的\n"
	.string "所有宝可梦。$"

gText_BadlyStartleFrontMon::
	.string "严重干扰在自己之前表演的\n"
	.string "宝可梦。$"

gText_BadlyStartleAppealed::
	.string "严重干扰表演完成的\n"
	.string "所有宝可梦。$"

gText_StartleAppealedBeforeUser2::
	.string "干扰在自己之前表演的\n"
	.string "宝可梦。$"

gText_StartleAllAppealed2::
	.string "干扰表演完成的\n"
	.string "所有宝可梦。$"

gText_ShiftJudgesAttentionFromOthers::
	.string "分散评委对之前宝可梦的\n"
	.string "注意。$"

gText_StartleMonHasJudgesAttention::
	.string "特别干扰评委注意的\n"
	.string "宝可梦。$"

gText_JamOthersMissesTurn::
	.string "激烈地干扰大家，\n"
	.string "但无法参加下一次表演。$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "特别干扰演出了相同类别的\n"
	.string "宝可梦。$"

gText_BadlyStartleCoolAppeals::
	.string "特别干扰演出了帅气招式的\n"
	.string "宝可梦。$"

gText_BadlyStartleBeautyAppeals::
	.string "特别干扰演出了美丽招式的\n"
	.string "宝可梦。$"

gText_BadlyStartleCuteAppeals::
	.string "特别干扰演出了可爱招式的\n"
	.string "宝可梦。$"

gText_BadlyStartleSmartAppeals::
	.string "特别干扰演出了聪明招式的\n"
	.string "宝可梦。$"

gText_BadlyStartleToughAppeals::
	.string "特别干扰演出了强壮招式的\n"
	.string "宝可梦。$"

gText_MakeMonAfterUserNervous::
	.string "让下一只表演的宝可梦\n"
	.string "感到紧张。$"

gText_MakeAllMonsAfterUserNervous::
	.string "让之后表演的所有宝可梦\n"
	.string "都感到紧张。$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "降低表演完成的\n"
	.string "宝可梦的气势。$"

gText_BadlyStartleMonsGoodCondition::
	.string "严重干扰气势良好的\n"
	.string "所有宝可梦。$"

gText_AppealGreatIfPerformedFirst::
	.string "最先演出时表演\n"
	.string "会更加吸引人。$"

gText_AppealGreatIfPerformedLast::
	.string "最后演出时表演\n"
	.string "会更加吸引人。$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "演出和此前所有宝可梦表演\n"
	.string "吸引力程度相当的表演。$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "和前一位宝可梦的\n"
	.string "表演一样吸引人。$"

gText_AppealBetterLaterItsPerformed::
	.string "演出时排序越靠后，\n"
	.string "越能演出吸引人的表演。$"

gText_AppealVariesDependingOnTiming::
	.string "每次演出的结果都不同。$"

gText_WorksWellIfSameTypeAsBefore::
	.string "和前一位宝可梦的表演类别\n"
	.string "相同时会更吸引人。$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "和前一位宝可梦的表演类别\n"
	.string "不同时会更吸引人。$"

gText_AffectedByAppealInFront::
	.string "演出水平受前一位宝可梦\n"
	.string "表演吸引程度的影响。$"

gText_UpsConditionHelpsPreventNervousness::
	.string "提升表演的气势，\n"
	.string "变得不容易感到紧张。$"

gText_AppealWorksWellIfConditionGood::
	.string "气势良好时表演\n"
	.string "会非常吸引人。$"

gText_NextAppealMadeEarlier::
	.string "下一次表演时最先出场。$"

gText_NextAppealMadeLater::
	.string "下一次表演时最后出场。$"

gText_TurnOrderMoreEasilyScrambled::
	.string "使下一次表演的顺序\n"
	.string "容易被打乱。$"

gText_ScrambleOrderOfNextAppeals::
	.string "打乱下一次表演的顺序。$"

gText_AppealExcitesAudienceInAnyContest::
	.string "任何类别的华丽大赛中\n"
	.string "都会让会场兴奋的表演。$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "严重干扰表演具有吸引力的\n"
	.string "所有宝可梦。$"

gText_AppealBestMoreCrowdExcited::
	.string "会场越兴奋，\n"
	.string "表演越吸引人。$"

gText_TemporarilyStopCrowdExcited::
	.string "表演后会场暂时不会\n"
	.string "变得更加兴奋。$"

@ Unused move names

gText_RainDance::
	.string "RAIN DANCE$"

gText_Rage::
	.string "RAGE$"

gText_FocusEnergy::
	.string "FOCUS ENERGY$"

gText_Hypnosis::
	.string "HYPNOSIS$"

gText_Softboiled::
	.string "SOFTBOILED$"

gText_HornAttack::
	.string "HORN ATTACK$"

gText_SwordsDance::
	.string "SWORDS DANCE$"

gText_Conversion::
	.string "CONVERSION$"

gText_SunnyDay::
	.string "SUNNY DAY$"

gText_Rest2::
	.string "REST$"

gText_Vicegrip::
	.string "VICEGRIP$"

gText_DefenseCurl::
	.string "DEFENSE CURL$"

gText_LockOn::
	.string "LOCK-ON$"

@ Contest type names

gContestMoveTypeCoolText::
	.string "帅气$"

gContestMoveTypeBeautyText::
	.string "美丽$"

gContestMoveTypeCuteText::
	.string "可爱$"

gContestMoveTypeSmartText::
	.string "聪明$"

gContestMoveTypeToughText::
	.string "强壮$"

gText_AppealNumWhichMoveWillBePlayed::
	.string "第{STR_VAR_1}回合的表演！\n"
	.string "要使用哪个招式呢？$"

gText_AppealNumButItCantParticipate::
	.string "第{STR_VAR_1}回合的表演！\n"
	.string "但是无法参加！$"

gText_MonAppealedWithMove::
	.string "{STR_VAR_1}使用了\n"
	.string "{STR_VAR_2}进行表演！$"

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1}在观察\n"
	.string "其他的宝可梦！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AllOutOfAppealTime::
	.string "表演时间结束！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

@ Unused appeal result texts

gText_ButAppealWasJammed::
	.string "But the appeal was\n"
	.string "jammed.$"

gText_FollowedAnotherMonsLead::
	.string "It followed another\n"
	.string "POKéMON's lead.$"

gText_ButItMessedUp::
	.string "But it messed up.$"

gText_WentBetterThanUsual::
	.string "It went better than\n"
	.string "usual.$"

gText_JudgeLookedAwayForSomeReason::
	.string "The JUDGE looked away\n"
	.string "for some reason.$"

gText_WorkedHardToBuildOnPastMistakes::
	.string "It worked hard to build on\n"
	.string "past mistakes.$"

gText_CantMakeAnyMoreMoves::
	.string "It can't make any more\n"
	.string "moves.$"

gText_WorkedFrighteninglyWell::
	.string "It worked frighteningly\n"
	.string "well.$"

gText_WorkedHardAsStandoutMon::
	.string "It worked as hard as the\n"
	.string "standout POKéMON.$"

gText_JudgedLookedOnExpectantly::
	.string "The JUDGE looked on\n"
	.string "expectantly.$"

gText_WorkedRatherWell::
	.string "It worked rather well.$"

gText_WorkedLittleBetterThanUsual::
	.string "It worked a little better\n"
	.string "than usual.$"

@ Round result texts

gText_MonFailedToStandOutAtAll::
	.string "{STR_VAR_1}\n"
	.string "完全没能获得关注……{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch::
	.string "{STR_VAR_1}\n"
	.string "表现平平无奇……{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention::
	.string "{STR_VAR_1}\n"
	.string "稍稍吸引了些许目光。{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention::
	.string "{STR_VAR_1}\n"
	.string "赢得了热烈的反响！{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention::
	.string "{STR_VAR_1}\n"
	.string "彻底成为了全场焦点！{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal::
	.string "{STR_VAR_1}\n"
	.string "没有参加表演……{PAUSE_UNTIL_PRESS}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2::
	.string "Anticipation swelled for\n"
	.string "{STR_VAR_1}'s appeal next.$"

gText_EmptyContestString::
	.string "$"

gText_JudgesViewsOnMonHeldFirm::
	.string "The JUDGE 's views on\n"
	.string "{STR_VAR_1} held firm.$"

gText_MonsXChangedPerceptions::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "changed perceptions.$"

gText_MonsAppealEffectWoreOff::
	.string "{STR_VAR_1}'s appeal\n"
	.string "effect wore off.$"

gText_SpecialAppealsEffectWoreOff::
	.string "The special appeal's\n"
	.string "effect wore off.$"

gText_EveryonesAppealsMadeToLookSame::
	.string "Everyone's appeals were\n"
	.string "made to look the same.$"

gText_CheapenedMonsAppeal::
	.string "It cheapened\n"
	.string "{STR_VAR_2}'s appeal.$"

gText_CheapenedAppealOfThoseAhead::
	.string "It cheapened the appeal\n"
	.string "of those ahead.$"

gText_StoleAttentionAwayFromMon::
	.string "It stole attention away\n"
	.string "from {STR_VAR_2}.$"

gText_CheapenedMonsAppeal2::
	.string "It cheapened\n"
	.string "{STR_VAR_2}'s appeal.$"

gText_SeverelyCheapenedOtherAppeals::
	.string "It severely cheapened\n"
	.string "other appeals.$"

gText_AnticipationSwelledForMonsAppealNext::
	.string "Anticipation swelled for\n"
	.string "{STR_VAR_1}'s appeal next.$"

gText_CheapenedAppealOfThoseAhead2::
	.string "It cheapened the appeal\n"
	.string "of those ahead.$"

gText_CheapenedJudgesFavoriteAppeal::
	.string "It cheapened the JUDGE's\n"
	.string "favorite appeal.$"

gText_AppealsOfOthersCheapenedByHalf::
	.string "The appeals of others\n"
	.string "were cheapened by half.$"

gText_StoodOutToMakeUpForBeingJammed::
	.string "It stood out to make up\n"
	.string "for being jammed.$"

gText_CantParticipateInAppealsAnyMore::
	.string "It can't participate in\n"
	.string "appeals any more.$"

gText_TouchedJudgeForFantasticAppeal::
	.string "It touched the JUDGE for\n"
	.string "a fantastic appeal.$"

gText_AnticipationRoseForUpcomingAppeals::
	.string "Anticipation rose for\n"
	.string "upcoming appeals.$"

gText_StoodOutAsMuchAsSpecialAppeals::
	.string "It stood out as much as\n"
	.string "special appeals.$"

gText_StoodOutAsMuchAsMon::
	.string "It stood out as much as\n"
	.string "{STR_VAR_1}老师。$"

gText_JammedAppealsMadeEvenLessNoticeable::
	.string "Jammed appeals were made\n"
	.string "even less noticeable.$"

gText_EveryonesAppealsMadeSame::
	.string "Everyone's appeals were\n"
	.string "made the same.$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
    .string "它变得比平时\n"
    .string "更加担心其他宝可梦了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
    .string "{STR_VAR_1}此后\n"
    .string "都无法再次进行表演了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
    .string "它稍微有些\n"
    .string "冷静下来了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
    .string "它变得完全\n"
    .string "不关注其他宝可梦了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
    .string "它变得不那么\n"
    .string "关注其他宝可梦了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
    .string "它不再那么\n"
    .string "留意其他宝可梦了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "它试图惊吓\n"
	.string "其他宝可梦！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
    .string "它试图让\n"
    .string "其他宝可梦眼花缭乱！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
    .string "评委的目光\n"
    .string "从{STR_VAR_1}身上移开了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
    .string "它试图让下一只\n"
    .string "表演的宝可梦紧张！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
    .string "{STR_VAR_1}\n"
    .string "紧张了起来！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
    .string "它试图让所有\n"
    .string "之后表演的宝可梦紧张！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
    .string "它嘲笑了\n"
    .string "气势良好的宝可梦！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
    .string "{STR_VAR_1}的气势\n"
    .string "回到了本来的样子！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
    .string "它试图干扰那些\n"
    .string "表演引人注目的宝可梦！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "本来就引人注目的\n"
	.string "{STR_VAR_1}更加鼓足干劲了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
    .string "原本不太引人注目的\n"
    .string "{STR_VAR_1}加油努力了起来！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
    .string "它鼓足了不会输给\n"
    .string "前面所有宝可梦程度的干劲！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
    .string "{STR_VAR_1}的表演\n"
    .string "没能成功奏效！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
    .string "和前面的宝可梦\n"
    .string "一样地鼓足了干劲！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
    .string "{STR_VAR_1}的表演\n"
    .string "没能成功奏效！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
    .string "{STR_VAR_1}的表演\n"
    .string "没能成功奏效！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
    .string "{STR_VAR_1}的表演\n"
    .string "做得还算可以！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
    .string "{STR_VAR_1}的表演\n"
    .string "做得不错！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
    .string "{STR_VAR_1}的表演\n"
    .string "做得非常出色！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
    .string "{STR_VAR_1}的表演\n"
    .string "完全失败了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
    .string "{STR_VAR_1}的表演\n"
    .string "做得不怎么好！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
    .string "{STR_VAR_1}的表演\n"
    .string "做得还算可以！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
    .string "{STR_VAR_1}的表演\n"
    .string "做得不错！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
    .string "{STR_VAR_1}的表演\n"
    .string "做得很好！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
    .string "{STR_VAR_1}的表演\n"
    .string "做得非常出色！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
    .string "因为和前面的宝可梦\n"
    .string "类别一致而受到喜欢！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
    .string "因为和前面的宝可梦\n"
    .string "类别不同而受到喜欢！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
    .string "比起前面的宝可梦\n"
    .string "要出彩得多！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
    .string "比起前面的宝可梦\n"
    .string "完成得不算太好！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
    .string "{STR_VAR_1}的气势\n"
    .string "比平时有所提升！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
    .string "{STR_VAR_1}气势不错，\n"
    .string "表演变得棒极了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "它想要在下回合的表演里\n"
	.string "更早出场而走到了前面！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "它想要在下回合的表演里\n"
	.string "更晚出场而后退了一步！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "下个回合的表演顺序\n"
	.string "变得奇怪了起来！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "评委满怀期待地\n"
	.string "看着{STR_VAR_1}！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverWell::
    .string "前后演出的招式组合\n"
	.string "得到了大家的喜爱！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverVeryWell::
    .string "前后演出的招式组合\n"
	.string "很受大家喜欢！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverExcellently::
    .string "前后演出的招式组合\n"
	.string "特别受大家喜欢！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonManagedToAvertGaze::
    .string "{STR_VAR_1}成功地\n"
    .string "移开了视线！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonManagedToAvoidSeeingIt::
    .string "{STR_VAR_1}成功地\n"
    .string "避开了视线！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonIsntFazedByThatSortOfThing::
    .string "{STR_VAR_1}没有受\n"
    .string "这种程度的事情影响！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameALittleDistracted::
    .string "{STR_VAR_1}变得\n"
    .string "稍稍有点分心了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherPokemon::
	.string "它试图惊吓\n"
	.string "其他宝可梦！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1}因为分心\n"
	.string "低下了头！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1}因为分心\n"
	.string "转过了身！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1}忍不住地\n"
	.string "叫出了声！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1}忍不住地\n"
	.string "跳了起来！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1}因为分心\n"
	.string "摔在了地上四脚朝天！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1}因为紧张\n"
	.string "无法使用招式表演了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItMessedUp2::
	.string "但它搞砸了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItFailedToMakeTargetNervous::
	.string "但是它没能让\n"
	.string "目标宝可梦紧张！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "但是它没能让\n"
	.string "任何宝可梦紧张！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItWasIgnored::
    .string "但它被无视了……{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_CouldntImproveItsCondition::
	.string "但是它并没能\n"
    .string "提升自己的气势……{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BadConditionResultedInWeakAppeal::
	.string "它因为气势不行\n"
    .string "表演得一点也不好……{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonWasUnaffected::
	.string "{STR_VAR_1}\n"
    .string "完全不为所动！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_RepeatedAppeal::
    .string "{STR_VAR_1}因为\n"
    .string "重复表演，让大家失望了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXWentOverGreat::
	.string "{STR_VAR_1}的{STR_VAR_3}表演\n"
	.string "受到了大家的热烈欢迎！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXDidntGoOverWell::
	.string "{STR_VAR_1}的{STR_VAR_3}表演\n"
	.string "在这里不受欢迎……{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXGotTheCrowdGoing::
	.string "{STR_VAR_1}的{STR_VAR_3}表演\n"
	.string "让整个会场沸腾了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1}无法参加\n"
    .string "下一次的表演了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AttractedCrowdsAttention::
	.string "吸引了\n"
    .string "观众们的注意！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_CrowdContinuesToWatchMon::
	.string "观众们一直\n"
    .string "持续关注着{STR_VAR_3}！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsMoveIsIgnored::
	.string "{STR_VAR_1}的{STR_VAR_2}\n"
    .string "被完全无视了……{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_Contest_Shyness::
    .string "扑通扑通$"

gText_Contest_Anxiety::
    .string "慌慌张张$"

gText_Contest_Laziness::
    .string "懒懒洋洋$"

gText_Contest_Hesitancy::
    .string "犹犹豫豫$"

gText_Contest_Fear::
	.string "战战栗栗$"

gText_Contest_Coolness::
	.string "帅气$"

gText_Contest_Beauty::
	.string "美丽$"

gText_Contest_Cuteness::
	.string "可爱$"

gText_Contest_Smartness::
	.string "聪明$"

gText_Contest_Toughness::
	.string "强壮$"

@ Unused
gText_Tension::
	.string "TENSION$"

gText_CoolMove::
	.string "COOL Move$"

gText_BeautyMove::
	.string "BEAUTY Move$"

gText_CuteMove::
	.string "CUTE Move$"

gText_SmartMove::
	.string "SMART Move$"

gText_ToughMove::
	.string "TOUGH Move$"

gText_3QuestionMarks::
	.string "???$"
