@ Contest move effect descriptions

gText_HighlyAppealingMove::
	.string "A highly appealing move.$"

gText_UserMoreEasilyStartled::
	.string "After this move, the user is\n"
	.string "more easily startled.$"

gText_GreatAppealButNoMoreToEnd::
	.string "Makes a great appeal, but\n"
	.string "allows no more to the end.$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "Can be repeatedly used\n"
	.string "without boring the JUDGE.$"

gText_AvoidStartledByOthersOnce::
	.string "Can avoid being startled\n"
	.string "by others once.$"

gText_AvoidStartledByOthers::
	.string "Can avoid being startled\n"
	.string "by others.$"

gText_AvoidStartledByOthersLittle::
	.string "Can avoid being startled\n"
	.string "by others a little.$"

gText_UserLessLikelyStartled::
	.string "After this move, the user is\n"
	.string "less likely to be startled.$"

gText_SlightlyStartleFrontMon::
	.string "Slightly startles the\n"
	.string "POKéMON in front.$"

gText_SlightlyStartleAppealed::
	.string "Slightly startles those\n"
	.string "that have made appeals.$"

gText_StartleAppealedBeforeUser::
	.string "Startles the POKéMON that\n"
	.string "appealed before the user.$"

gText_StartleAllAppealed::
	.string "Startles all POKéMON that\n"
	.string "have done their appeals.$"

gText_BadlyStartleFrontMon::
	.string "Badly startles the\n"
	.string "POKéMON in front.$"

gText_BadlyStartleAppealed::
	.string "Badly startles those that\n"
	.string "have made appeals.$"

gText_StartleAppealedBeforeUser2::
	.string "Startles the POKéMON that\n"
	.string "appealed before the user.$"

gText_StartleAllAppealed2::
	.string "Startles all POKéMON that\n"
	.string "have done their appeals.$"

gText_ShiftJudgesAttentionFromOthers::
	.string "Shifts the JUDGE's\n"
	.string "attention from others.$"

gText_StartleMonHasJudgesAttention::
	.string "Startles the POKéMON that\n"
	.string "has the JUDGE's attention.$"

gText_JamOthersMissesTurn::
	.string "Jams the others, and misses\n"
	.string "one turn of appeals.$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "Startles POKéMON that\n"
	.string "made a same-type appeal.$"

gText_BadlyStartleCoolAppeals::
	.string "Badly startles POKéMON\n"
	.string "that made COOL appeals.$"

gText_BadlyStartleBeautyAppeals::
	.string "Badly startles POKéMON\n"
	.string "that made BEAUTY appeals.$"

gText_BadlyStartleCuteAppeals::
	.string "Badly startles POKéMON\n"
	.string "that made CUTE appeals.$"

gText_BadlyStartleSmartAppeals::
	.string "Badly startles POKéMON\n"
	.string "that made SMART appeals.$"

gText_BadlyStartleToughAppeals::
	.string "Badly startles POKéMON\n"
	.string "that made TOUGH appeals.$"

gText_MakeMonAfterUserNervous::
	.string "Makes one POKéMON after\n"
	.string "the user nervous.$"

gText_MakeAllMonsAfterUserNervous::
	.string "Makes all POKéMON after\n"
	.string "the user nervous.$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "Worsens the condition of\n"
	.string "those that made appeals.$"

gText_BadlyStartleMonsGoodCondition::
	.string "Badly startles POKéMON in\n"
	.string "good condition.$"

gText_AppealGreatIfPerformedFirst::
	.string "The appeal works great if\n"
	.string "performed first.$"

gText_AppealGreatIfPerformedLast::
	.string "The appeal works great if\n"
	.string "performed last.$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "Makes the appeal as good\n"
	.string "as those before it.$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "Makes the appeal as good\n"
	.string "as the one before it.$"

gText_AppealBetterLaterItsPerformed::
	.string "The appeal works better\n"
	.string "the later it is performed.$"

gText_AppealVariesDependingOnTiming::
	.string "The appeal's quality varies\n"
	.string "depending on its timing.$"

gText_WorksWellIfSameTypeAsBefore::
	.string "Works well if it's the same\n"
	.string "type as the one before.$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "Works well if different in\n"
	.string "type than the one before.$"

gText_AffectedByAppealInFront::
	.string "Affected by how well the\n"
	.string "appeal in front goes.$"

gText_UpsConditionHelpsPreventNervousness::
	.string "Ups the user's condition.\n"
	.string "Helps prevent nervousness.$"

gText_AppealWorksWellIfConditionGood::
	.string "The appeal works well if the\n"
	.string "user's condition is good.$"

gText_NextAppealMadeEarlier::
	.string "The next appeal can be\n"
	.string "made earlier next turn.$"

gText_NextAppealMadeLater::
	.string "The next appeal can be\n"
	.string "made later next turn.$"

gText_TurnOrderMoreEasilyScrambled::
	.string "Makes the next turn's order\n"
	.string "more easily scrambled.$"

gText_ScrambleOrderOfNextAppeals::
	.string "Scrambles the order of\n"
	.string "appeals on the next turn.$"

gText_AppealExcitesAudienceInAnyContest::
	.string "An appeal that excites the\n"
	.string "audience in any CONTEST.$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "Badly startles all POKéMON\n"
	.string "that made good appeals.$"

gText_AppealBestMoreCrowdExcited::
	.string "The appeal works best the\n"
	.string "more the crowd is excited.$"

gText_TemporarilyStopCrowdExcited::
	.string "Temporarily stops the\n"
	.string "crowd from growing excited.$"

@ Unused move names

gText_RainDance::
	.string "RAIN DANCE$"

gText_Rage::
	.string "RAGE$"

gText_FocusEnergy::
	.string "FOCUS ENERGY$"

gText_Hypnosis::
	.string "HYPNOSIS$"

gText_Softboiled::
	.string "SOFTBOILED$"

gText_HornAttack::
	.string "HORN ATTACK$"

gText_SwordsDance::
	.string "SWORDS DANCE$"

gText_Conversion::
	.string "CONVERSION$"

gText_SunnyDay::
	.string "SUNNY DAY$"

gText_Rest2::
	.string "REST$"

gText_Vicegrip::
	.string "VICEGRIP$"

gText_DefenseCurl::
	.string "DEFENSE CURL$"

gText_LockOn::
	.string "LOCK-ON$"

@ Contest type names

gContestMoveTypeCoolText::
	.string "COOL$"

gContestMoveTypeBeautyText::
	.string "BEAUTY$"

gContestMoveTypeCuteText::
	.string "CUTE$"

gContestMoveTypeSmartText::
	.string "SMART$"

gContestMoveTypeToughText::
	.string "TOUGH$"

gText_AppealNumWhichMoveWillBePlayed::
	.string "第{STR_VAR_1}回合的表演！\n"
	.string "要使用哪个招式呢？$"

gText_AppealNumButItCantParticipate::
	.string "第{STR_VAR_1}回合的表演！\n"
	.string "但是无法参加！$"

gText_MonAppealedWithMove::
	.string "{STR_VAR_1}使用了\n"
	.string "{STR_VAR_2}进行表演！$"

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1}在观察\n"
	.string "其他的宝可梦！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AllOutOfAppealTime::
	.string "表演时间结束！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

@ Unused appeal result texts

gText_ButAppealWasJammed::
	.string "But the appeal was\n"
	.string "jammed.$"

gText_FollowedAnotherMonsLead::
	.string "It followed another\n"
	.string "POKéMON's lead.$"

gText_ButItMessedUp::
	.string "But it messed up.$"

gText_WentBetterThanUsual::
	.string "It went better than\n"
	.string "usual.$"

gText_JudgeLookedAwayForSomeReason::
	.string "The JUDGE looked away\n"
	.string "for some reason.$"

gText_WorkedHardToBuildOnPastMistakes::
	.string "It worked hard to build on\n"
	.string "past mistakes.$"

gText_CantMakeAnyMoreMoves::
	.string "It can't make any more\n"
	.string "moves.$"

gText_WorkedFrighteninglyWell::
	.string "It worked frighteningly\n"
	.string "well.$"

gText_WorkedHardAsStandoutMon::
	.string "It worked as hard as the\n"
	.string "standout POKéMON.$"

gText_JudgedLookedOnExpectantly::
	.string "The JUDGE looked on\n"
	.string "expectantly.$"

gText_WorkedRatherWell::
	.string "It worked rather well.$"

gText_WorkedLittleBetterThanUsual::
	.string "It worked a little better\n"
	.string "than usual.$"

@ Round result texts

gText_MonFailedToStandOutAtAll::
	.string "{STR_VAR_1} failed to\n"
	.string "stand out at all…{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch::
	.string "{STR_VAR_1} didn't stand\n"
	.string "out very much…{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention::
	.string "{STR_VAR_1} caught a\n"
	.string "little attention.{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention::
	.string "{STR_VAR_1} attracted a\n"
	.string "lot of attention.{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention::
	.string "{STR_VAR_1} commanded\n"
	.string "total attention.{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal::
	.string "{STR_VAR_1} hasn't made\n"
	.string "its appeal.{PAUSE_UNTIL_PRESS}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2::
	.string "Anticipation swelled for\n"
	.string "{STR_VAR_1}'s appeal next.$"

gText_EmptyContestString::
	.string "$"

gText_JudgesViewsOnMonHeldFirm::
	.string "The JUDGE 's views on\n"
	.string "{STR_VAR_1} held firm.$"

gText_MonsXChangedPerceptions::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "changed perceptions.$"

gText_MonsAppealEffectWoreOff::
	.string "{STR_VAR_1}'s appeal\n"
	.string "effect wore off.$"

gText_SpecialAppealsEffectWoreOff::
	.string "The special appeal's\n"
	.string "effect wore off.$"

gText_EveryonesAppealsMadeToLookSame::
	.string "Everyone's appeals were\n"
	.string "made to look the same.$"

gText_CheapenedMonsAppeal::
	.string "It cheapened\n"
	.string "{STR_VAR_2}'s appeal.$"

gText_CheapenedAppealOfThoseAhead::
	.string "It cheapened the appeal\n"
	.string "of those ahead.$"

gText_StoleAttentionAwayFromMon::
	.string "It stole attention away\n"
	.string "from {STR_VAR_2}.$"

gText_CheapenedMonsAppeal2::
	.string "It cheapened\n"
	.string "{STR_VAR_2}'s appeal.$"

gText_SeverelyCheapenedOtherAppeals::
	.string "It severely cheapened\n"
	.string "other appeals.$"

gText_AnticipationSwelledForMonsAppealNext::
	.string "Anticipation swelled for\n"
	.string "{STR_VAR_1}'s appeal next.$"

gText_CheapenedAppealOfThoseAhead2::
	.string "It cheapened the appeal\n"
	.string "of those ahead.$"

gText_CheapenedJudgesFavoriteAppeal::
	.string "It cheapened the JUDGE's\n"
	.string "favorite appeal.$"

gText_AppealsOfOthersCheapenedByHalf::
	.string "The appeals of others\n"
	.string "were cheapened by half.$"

gText_StoodOutToMakeUpForBeingJammed::
	.string "It stood out to make up\n"
	.string "for being jammed.$"

gText_CantParticipateInAppealsAnyMore::
	.string "It can't participate in\n"
	.string "appeals any more.$"

gText_TouchedJudgeForFantasticAppeal::
	.string "It touched the JUDGE for\n"
	.string "a fantastic appeal.$"

gText_AnticipationRoseForUpcomingAppeals::
	.string "Anticipation rose for\n"
	.string "upcoming appeals.$"

gText_StoodOutAsMuchAsSpecialAppeals::
	.string "It stood out as much as\n"
	.string "special appeals.$"

gText_StoodOutAsMuchAsMon::
	.string "It stood out as much as\n"
	.string "{STR_VAR_1}老师。$"

gText_JammedAppealsMadeEvenLessNoticeable::
	.string "Jammed appeals were made\n"
	.string "even less noticeable.$"

gText_EveryonesAppealsMadeSame::
	.string "Everyone's appeals were\n"
	.string "made the same.$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
    .string "它变得比平时\n"
    .string "更加担心其他宝可梦了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
    .string "{STR_VAR_1}此后\n"
    .string "都无法再次进行表演了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
    .string "它稍微有些\n"
    .string "冷静下来了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
    .string "它变得完全\n"
    .string "不关注其他宝可梦了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
    .string "它变得不那么\n"
    .string "关注其他宝可梦了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
    .string "它不再那么\n"
    .string "留意其他宝可梦了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "它试图惊吓\n"
	.string "其他宝可梦！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
    .string "它试图让\n"
    .string "其他宝可梦眼花缭乱！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
    .string "评委的目光\n"
    .string "从{STR_VAR_1}身上移开了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
    .string "它试图让下一只\n"
    .string "表演的宝可梦紧张！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
    .string "{STR_VAR_1}\n"
    .string "紧张了起来！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
    .string "它试图让所有\n"
    .string "之后表演的宝可梦紧张！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
    .string "它嘲笑了\n"
    .string "气势良好的宝可梦！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
    .string "{STR_VAR_1}的气势\n"
    .string "回到了本来的样子！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
    .string "它试图干扰那些\n"
    .string "表演引人注目的宝可梦！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "本来就引人注目的\n"
	.string "{STR_VAR_1}更加鼓足干劲了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
    .string "原本不太引人注目的\n"
    .string "{STR_VAR_1}加油努力了起来！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
    .string "它鼓足了不会输给\n"
    .string "前面所有宝可梦程度的干劲！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
    .string "{STR_VAR_1}的表演\n"
    .string "没能成功奏效！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
    .string "和前面的宝可梦\n"
    .string "一样地鼓足了干劲！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
    .string "{STR_VAR_1}的表演\n"
    .string "没能成功奏效！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
    .string "{STR_VAR_1}的表演\n"
    .string "没能成功奏效！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
    .string "{STR_VAR_1}的表演\n"
    .string "做得还算可以！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
    .string "{STR_VAR_1}的表演\n"
    .string "做得不错！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
    .string "{STR_VAR_1}的表演\n"
    .string "做得非常出色！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
    .string "{STR_VAR_1}的表演\n"
    .string "完全失败了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
    .string "{STR_VAR_1}的表演\n"
    .string "做得不怎么好！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
    .string "{STR_VAR_1}的表演\n"
    .string "做得还算可以！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
    .string "{STR_VAR_1}的表演\n"
    .string "做得不错！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
    .string "{STR_VAR_1}的表演\n"
    .string "做得很好！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
    .string "{STR_VAR_1}的表演\n"
    .string "做得非常出色！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
    .string "因为和前面的宝可梦\n"
    .string "类别一致而受到喜欢！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
    .string "因为和前面的宝可梦\n"
    .string "类别不同而受到喜欢！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
    .string "比起前面的宝可梦\n"
    .string "要出彩得多！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
    .string "比起前面的宝可梦\n"
    .string "完成得不算太好！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
    .string "{STR_VAR_1}的气势\n"
    .string "比平时有所提升！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
    .string "{STR_VAR_1}气势不错，\n"
    .string "表演变得棒极了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "它想要在下回合的表演里\n"
	.string "更早出场而走到了前面！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "它想要在下回合的表演里\n"
	.string "更晚出场而后退了一步！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "下个回合的表演顺序\n"
	.string "变得奇怪了起来！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "评委满怀期待地\n"
	.string "看着{STR_VAR_1}！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverWell::
    .string "前后演出的招式组合\n"
	.string "得到了大家的喜爱！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverVeryWell::
    .string "前后演出的招式组合\n"
	.string "很受大家喜欢！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverExcellently::
    .string "前后演出的招式组合\n"
	.string "特别受大家喜欢！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonManagedToAvertGaze::
    .string "{STR_VAR_1}成功地\n"
    .string "移开了视线！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonManagedToAvoidSeeingIt::
    .string "{STR_VAR_1}成功地\n"
    .string "避开了视线！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonIsntFazedByThatSortOfThing::
    .string "{STR_VAR_1}没有受\n"
    .string "这种程度的事情影响！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameALittleDistracted::
    .string "{STR_VAR_1}变得\n"
    .string "稍稍有点分心了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherPokemon::
	.string "它试图惊吓\n"
	.string "其他宝可梦！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1}因为分心\n"
	.string "低下了头！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1}因为分心\n"
	.string "转过了身！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1}忍不住地\n"
	.string "叫出了声！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1}忍不住地\n"
	.string "跳了起来！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1}因为分心\n"
	.string "摔在了地上四脚朝天！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1}因为紧张\n"
	.string "无法使用招式表演了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItMessedUp2::
	.string "但它搞砸了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItFailedToMakeTargetNervous::
	.string "但是它没能让\n"
	.string "目标宝可梦紧张！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "但是它没能让\n"
	.string "任何宝可梦紧张！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItWasIgnored::
    .string "但它被无视了……{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_CouldntImproveItsCondition::
	.string "但是它并没能\n"
    .string "提升自己的气势……{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BadConditionResultedInWeakAppeal::
	.string "它因为气势不行\n"
    .string "表演得一点也不好……{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonWasUnaffected::
	.string "{STR_VAR_1}\n"
    .string "完全不为所动！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_RepeatedAppeal::
    .string "{STR_VAR_1}因为\n"
    .string "重复表演，让大家失望了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXWentOverGreat::
	.string "{STR_VAR_1}的{STR_VAR_3}表演\n"
	.string "受到了大家的热烈欢迎！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXDidntGoOverWell::
	.string "{STR_VAR_1}的{STR_VAR_3}表演\n"
	.string "在这里不受欢迎……{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXGotTheCrowdGoing::
	.string "{STR_VAR_1}的{STR_VAR_3}表演\n"
	.string "让整个会场沸腾了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1}无法参加\n"
    .string "下一次的表演了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AttractedCrowdsAttention::
	.string "吸引了\n"
    .string "观众们的注意！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_CrowdContinuesToWatchMon::
	.string "观众们一直\n"
    .string "持续关注着{STR_VAR_3}！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsMoveIsIgnored::
	.string "{STR_VAR_1}的{STR_VAR_2}\n"
    .string "被完全无视了……{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_Contest_Shyness::
    .string "扑通扑通$"

gText_Contest_Anxiety::
    .string "慌慌张张$"

gText_Contest_Laziness::
    .string "懒懒洋洋$"

gText_Contest_Hesitancy::
    .string "犹犹豫豫$"

gText_Contest_Fear::
	.string "战战栗栗$"

gText_Contest_Coolness::
	.string "coolness$"

gText_Contest_Beauty::
	.string "beauty$"

gText_Contest_Cuteness::
	.string "cuteness$"

gText_Contest_Smartness::
	.string "smartness$"

gText_Contest_Toughness::
	.string "toughness$"

@ Unused
gText_Tension::
	.string "TENSION$"

gText_CoolMove::
	.string "COOL Move$"

gText_BeautyMove::
	.string "BEAUTY Move$"

gText_CuteMove::
	.string "CUTE Move$"

gText_SmartMove::
	.string "SMART Move$"

gText_ToughMove::
	.string "TOUGH Move$"

gText_3QuestionMarks::
	.string "???$"
