@ Battle Tower
gText_AnabelWonSilver::
	.string "好令人失望……$"

gText_AnabelDefeatSilver::
	.string "好的，我知道了……$"

gText_AnabelWonGold::
	.string "我真的很抱歉……$"

gText_AnabelDefeatGold::
	.string "谢谢你……$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "啊哈哈！你不尴尬吗？\n"
	.string "所有人都在看着呢！$"

gText_TuckerDefeatSilver::
	.string "呃……\n"
	.string "怎么回……$"

gText_TuckerWonGold::
	.string "我巨蛋超级巨星\n"
	.string "可不是浪得虚名！$"

gText_TuckerDefeatGold::
	.string "啊哈哈！\n"
	.string "你给我带来了灵感！$"

@ Battle Factory
gText_NolandWonSilver::
	.string "干得好！\n"
	.string "这也是不错的一课，对吧？$"

gText_NolandDefeatSilver::
	.string "好样的！\n"
	.string "你知道自己在做什么！$"

gText_NolandWonGold::
	.string "喂，喂，喂！\n"
	.string "你已经结束了吗？$"

gText_NolandDefeatGold::
	.string "这里发生了什么？$"

@ Battle Pike
gText_LucyWonSilver::
	.string "哼……$"

gText_LucyDefeatSilver::
	.string "呃……$"

gText_LucyWonGold::
	.string "哈！$"

gText_LucyDefeatGold::
	.string "可恶！$"

@ Battle Arena
gText_GretaWonSilver::
	.string "喂，加把劲！\n"
	.string "你得做得更好才行！$"

gText_GretaDefeatSilver::
	.string "没想到！\n"
	.string "好样的！$"

gText_GretaWonGold::
	.string "嘿嘿嘿！\n"
	.string "你在期待什么？$"

gText_GretaDefeatGold::
	.string "啊？\n"
	.string "你认真的？！$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "你的宝可梦之所以弱小，\n"
	.string "是因为你是个弱小的训练家。$"

gText_SpenserDefeatSilver::
	.string "啊……\n"
	.string "这下可不一样了。$"

gText_SpenserWonGold::
	.string "唔哈哈哈！\n"
	.string "弟兄们，我们无所畏惧！$"

gText_SpenserDefeatGold::
	.string "咕啊！\n"
	.string "哈哈哈哈！$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "嘿！你怎么了！\n"
	.string "让我看看你的毅力！站起来！$"

gText_BrandonDefeatSilver::
	.string "就是这样！做得很棒！\n"
	.string "你有为此好好努力！$"

gText_BrandonWonGold::
	.string "嘿！不要放弃！\n"
	.string "站起来！别对自己丧失信心！$"

gText_BrandonDefeatGold::
	.string "就是这样！你做到了！\n"
	.string "你有一直不懈地努力！$"
